type: php
docroot: .Build
webserver_type: apache-fpm
additional_hostnames:
  - 12.solr-dashboard-widgets
  - 13.solr-dashboard-widgets
  - 14.solr-dashboard-widgets
hooks:
   post-start:
    - exec: mkdir -p /var/www/html/.Build/ && cp /var/www/html/.ddev/.setup/templates/* /var/www/html/.Build/
