name: solr-dashboard-widgets
type: php
docroot: .Build
php_version: "8.2"
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames:
  - 12.solr-dashboard-widgets
  - 13.solr-dashboard-widgets
  - 14.solr-dashboard-widgets
additional_fqdns: []
database:
  type: mariadb
  version: "11.4"
webimage_extra_packages: [libxml2-utils, php8.4-pcov]
use_dns_when_possible: true
composer_version: "2"
nodejs_version: "16"
corepack_enable: false
hooks:
  post-start:
    - exec: mkdir -p /var/www/html/.Build/ && cp /var/www/html/.ddev/.setup/templates/* /var/www/html/.Build/
