services:
  solr:
    image: typo3solr/ext-solr:13.0.2
    container_name: ddev-${DDEV_SITENAME}-solr
    hostname: solr
    expose:
      - "8983"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
    environment:
      - SOLR_JAVA_MEM=-Xms512m -Xmx512m
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=8982:8983
      - HTTPS_EXPOSE=8943:8983
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8983/solr/admin/cores?action=STATUS || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 30s
